api/urls.py
from django.urls import path,include
from rest_framework import routers,views

from . import views

router = routers.DefaultRouter()
router.register('User',views.UserViewSet)

urlpatterns = [
    path('',include(router.urls)),
]

mysite/urls.py
from re import template
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.generic import TemplateView,RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('api/',include('api.urls')),
]
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
    path('',TemplateView.as_view(template_name='index.html')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.jwt')),
    path('api/v1/', include('api.urls')),
    re_path('', RedirectView.as_view(url='/')),
]
"""

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('',views.Top.as_view(),name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

api/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.db.models.fields import DateField
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    
    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return self.first_name + self.last_name

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name + self.last_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.first_name + self.last_name
   
    def __str__(self):
        return self.first_name + self.last_name

user/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model

User = get_user_model()

class EmailChangeForm(forms.ModelForm):
    """メールアドレス変更フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

api/views.py
from rest_framework import serializers, viewsets
from rest_framework import permissions
from rest_framework.permissions import IsAuthenticatedOrReadOnly,IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend

from user.models import User
from api.serializer import UserSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['id']

user/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailChangeForm
)

User = get_user_model()

class Top(generic.TemplateView):
    template_name = 'user/top.html'

class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'user/login.html'

class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'user/top.html'

user/templates/user/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- vuetify -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@6.x/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hirota's Parsonal Home Page</title>
</head>
<body>

  <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #3F51B5;">
      <div class="container">
        <a class="navbar-brand" href="{% url 'user:top' %}">Hirota's Parsonal Home Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

          {% if user.is_authenticated %}    
          <!-- この下の行に mr-auto クラスを付与するだけ -->
          <ul class="navbar-nav mr-auto">　
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:top' %}">Home</a>
            </li>
            <!-- 経理アカウントで報告ベースを作成できるようにする -->
            {% if user.authority == "経理" %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'report:report_init' %}">報告書作成</a>
            </li>            
            {% endif %}
          </ul>
    
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               ようこそ、{{ user }} さん
             </a>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
               <div class="dropdown-divider"></div>
             </div>
            </li>
          </ul>

          <!-- ログイン前の表示処理 -->
          {% else %}

          <ul class="navbar-nav mr-auto">　
            <li class="nav-item">
            </li>
          </ul>
          <ul class="navbar-nav">　
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">ここからログイン</a>
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
      {% block content %}{% endblock %}
    </div>
  
  </div>
    <!-- フッター -->
    <footer class="footer">
      <div class="container">
        <p class="text-white">© 2022 ～ Masafumi Hirota</p>
      </div>
    </footer>
</body>
</html>

user/templates/user/login.html
{% extends "user/base.html" %}
{% block content %}

<div id="app">
    <v-app>
        <v-main>
            <v-container>
              <v-row>
                <v-col>
                    <v-card width="800px">
                        <v-container>
                            <v-row>
                              <v-col>
                                <form action="{% url 'user:login' %}" method="POST">
                                    <v-card-title>
                                        ログイン
                                    </v-card-title>

                                    <v-card-text>
                                        {{ form.non_field_errors }}
                                        {% for field in form %}
                                            {{ field.label }}<p></p>
                                            {{ field }}
                                            {{ field.errors }}
                                            <hr><p></p>
                                        {% endfor %}
                                        <v-btn
                                            type="submit"
                                            dark
                                            color="indigo"
                                            elevation="4">
                                            Login
                                            <v-icon color="white" dark>
                                                mdi-login-variant
                                            </v-icon>
                                        </v-btn>
                                        <input type="hidden" name="next" value="{{ next }}" />
                                        {% csrf_token %}
                                    </v-card-text>
                                </form>
                            </v-clo>
                        </v-row>
                      </v-container>          
                    </v-card>
                </v-clo>
              </v-row>
            </v-container>
        </v-main>
    </v-app>
</div>

  <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
  <script>
    new Vue({
      el: '#app',
      vuetify: new Vuetify(),
      delimiters: ["[[","]]"],
      data:{
          test:1265161653,
          aaa:"",
      }
    })
  </script>
{% endblock %}

user/templates/user/top.html
{% extends "user/base.html" %}
{% block content %}

<div id="app">
    <v-app>
    {% if user.is_authenticated %}

    <v-main>
        <v-container>
          {% if user.initial_setting == False %}
          <v-row>
            <v-col>
              <a href="{% url 'report:initial_setting' %}">こちらから初期設定をおこなってください</a>
            </v-clo>
          </v-row>

          {% else %}
          <v-row>
            <v-col>
              {{ text }}
            </v-col>
          </v-row>

          <v-row>
            <v-col>
              {% if flag == True %}
                {% for i in report %}
                  <a href="{% url 'report:report_detail' i.pk %}">{{ i.Year }} 年 {{ i.Month }} 月分 {{ i.Approval_name }}</a>              
                {% endfor %}
              {% else %}
                {% for i in report %}
                  {{ i.Year }} 年 {{ i.Month }} 月分 {{ i.Approval_name }}
                {% endfor %}
              {% endif %}
            </v-clo>
          </v-row>
          <v-row>
            <v-col>
              <h3>[[ test ]]</h3>
            </v-clo>
          </v-row>
          <v-row>
            <v-col>
          </v-row>
          {% endif %}
        </v-container>
    </v-main>

    {% else %}
    <v-main>
        <v-container>
          <v-row>
            <v-col>
              右上からログインをしてください
            </v-clo>
          </v-row>
        </v-container>
    </v-main>
    {% endif %}

    </v-app>
</div>

<script>
    new Vue({
      el: '#app',
      vuetify: new Vuetify(),
      delimiters: ["[[","]]"],
      data:{
          test:1265161653,
          aaa:"",
      },
      methods:{

      },
    })
  </script>

{% endblock %}